### ISSUE TITLE
quick test failure on fresh debian 6.0  install

### ISSUE THREAD

**Issue by jnavila** [ptitfred/magrit#4]
``` shell
[jnavila@coriandre Téléchargement]$ . /tmp/magrit-quick/setup.sh 
[jnavila@coriandre Téléchargement]$ sh /tmp/magrit-quick/start.sh 
Exception in thread "main" java.util.NoSuchElementException
   at java.util.AbstractList$2.next(libgcj.so.10)
   at com.google.inject.spi.InjectionPoint.forMember(InjectionPoint.java:114)
   at com.google.inject.spi.InjectionPoint.<init>(InjectionPoint.java:78)
   at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:272)
   at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:96)
   at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:629)
   at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:845)
   at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
   at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
   at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
   at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
   at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:46)
   at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:50)
   at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:133)
   at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
   at com.google.inject.Guice.createInjector(Guice.java:95)
   at com.google.inject.Guice.createInjector(Guice.java:72)
   at com.google.inject.Guice.createInjector(Guice.java:62)
   at org.kercoin.magrit.Magrit.bootStrap(Magrit.java:32)
   at org.kercoin.magrit.Magrit.<init>(Magrit.java:28)
   at org.kercoin.magrit.Magrit.main(Magrit.java:151)
```

Is it needed to install Oracle java?

**Comment by ptitfred** [comment]
Indeed all my tests as of now are done under Sun JRE or OpenJDK (which is basically the same).

Edit: version 1.6.x

**Comment by ptitfred** [comment]
GCJ doesn't fully support 1.5+ Java language features and basically fails on generics from the Java Collection API ... so I guess Magrit won't support GCJ.

OpenJDK is the official Java implementation, released under GPL and available in Debian repositories.

Please note that Sun/Oracle JVM isn't released under a compliant license anymore so it's missing from Debian repositories. But that won't be a problem for Magrit : OpenJDK is fine.
